// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whiweucqeogodlsabwxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoaXdldWNxZW9nb2Rsc2Fid3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDc3NTksImV4cCI6MjA3MDA4Mzc1OX0.qvKuhpzm8mccCbt9DYtZz4VLInKZkl0YRJb-iqSqMAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});